name: vka_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  envied: ^0.5.4
  supabase: ^2.5.0
  vcq_models:
         git:
           url: https://github.com/tonyOkumura/VCQ_models.git
           ref: c788b23
 


dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.13
